### ISSUE TITLE
Tracer to omit non-js entry files

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [jspm/rollup-plugin-jspm#14]
I am trying to use the plugin with `vitejs` which uses `index.html` as entry point. And the tracer only works with JS code. Not sure how to solve this, but would like to help if there is a way to omit tracing `non-js` files for `import` detection.

Here is a repo that setup using `rollup` as well as `vitejs`. You can use `yarn build` for rollup and `yarn vitejs:build` for using from `jspm`

https://github.com/JayaKrishnaNamburu/importmap-rollup-vitejs-jspm#readme

I am not sure, which will be the right place to fix this. Either in `generator` here
https://github.com/jspm/generator/blob/main/src/trace/tracemap.ts#L347-L349

or in this plugin itself. And not invoke `traceInstall` for non-js extensions
https://github.com/jspm/rollup-plugin-jspm/blob/main/jspm-rollup.js#L114

**Comment by guybedford** [comment]
@JayaKrishnaNamburu HTML generation was recently added to the Generator in https://github.com/jspm/generator#generating-html. Can you achieve your goals with this approach?

**Comment by JayaKrishnaNamburu** [comment]
Sounds like something, fit for the use-case. I will give a try 👍

**Comment by guybedford** [comment]
Okay, just let me know if it doesn't meet your needs here and we can discuss any new features as necessary.

**Comment by JayaKrishnaNamburu** [comment]
So, looks like. The way the plugins works, it's best for rollup setups. Bute for `vitejs`, not of much use. Since, `vitejs` doesn't call `resolveId` hook from rollup plugins and uses some internal hook. And so, the plugin is not able to `trace` properly.

With rollup `buildStart` -> `resolveId` -> `load` -> `transform`
With vitejs `buildStart` -> `load` -> `transform`

https://github.com/vitejs/vite/issues/1899
https://github.com/vitejs/vite/issues/5981

**Comment by guybedford** [comment]
@JayaKrishnaNamburu I wouldn't recommend trying to get the plugin to work within Vite. Rather I would advise not using Vite for these reasons.

**Comment by JayaKrishnaNamburu** [comment]
Yup, i till feel the same. Too many constraints and off the life cycle of what we used to 😅. Closing this, thank you 😄
