### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by fusionstrings** [jspm/rollup-plugin-jspm#15]
running `npm run test` fails.

```sh
  Basic Rollup
    1) Test


  0 passing (339ms)
  1 failing

  1) Basic Rollup
       Test:
     TypeError: url.startsWith is not a function
```

**Comment by guybedford** [comment]
Tried this and all I needed to get the tests to pass was https://github.com/jspm/rollup-plugin-jspm/commit/3795ba202f64900f6f9da842721fdeef37bcc97e. Otherwise can you share a replication?

**Comment by guybedford** [comment]
Ah, turns out there were some other changes needed in https://github.com/jspm/rollup-plugin-jspm/commit/ce3bb24cb45e6c5c306922de7ef21b6a4390bbdb.

Then there are still a couple of errors unfortunately. The next generator version will fix these!

**Comment by guybedford** [comment]
This is now fixed with the master version of the generator. The next release will be at the latest Tuesday next week. Thanks for bringing this to my attention!
