### ISSUE TITLE
Question: Is it expected to install babel presets as npm dependency?

### ISSUE THREAD

**Issue by fusionstrings** [jspm/rollup-plugin-jspm#7]
I tried to use babel presets using `jspm install @babel/preset-react`but it failed with following error-

```bash
(babel plugin) Error: Cannot find module '@babel/preset-react' from '/Users/dilip/@fusionstrings/jspm-fix-test'
```

When I install these dependencies using npm, it works. Is it expected behaviour? All other dependencies i.e. react, react-dom is installed using jspm.

**Comment by guybedford** [comment]
Is this following the workflow from https://jspm.org/docs/integrations#rollup?

Note that it is important that Rollup itself is installed and run with jspm for this to work.

**Comment by fusionstrings** [comment]
Right, I am following the same guide. I am getting following error during building.
```bash
[!] (babel plugin) Error: Cannot find module '@babel/preset-react' from '/Users/dilip/github/@fusionstrings/jspm-beta-issue-require-not-found'
``` 

This is the repository https://github.com/fusionstrings/jspm-beta-issue-require-not-found
After installing babel-presets using npm, it worked

**Comment by guybedford** [comment]
The issue you are having here is exactly the issue described in the Babel integration section here - https://jspm.org/docs/integrations#babel.

**Comment by guybedford** [comment]
(With tracking issue for Babel at https://github.com/babel/babel/issues/9888)

**Comment by fusionstrings** [comment]
aha, I thought it's the case only when files are processed directly with babel cli because it's not mentioned under rollup integration.
