### ISSUE TITLE
difference and error in build compared to jspm build

### ISSUE THREAD

**Issue by fusionstrings** [jspm/rollup-plugin-jspm#8]
I followed the guide https://jspm.org/docs/integrations#rollup.

Issue can be reproduced by cloning https://github.com/fusionstrings/jspm-react-rollup and building `npm run build`, which showcases difference between jspm build and rollup build using `rollup-plugin-jspm`.

[JSPM build](https://github.com/fusionstrings/jspm-react-rollup/blob/master/dist/jspm/main.js) outputs differently than [Rollup build](dist/jspm/main.js).

The difference per se is not my concern but rollup build adds dependency of 'process' module, which results into error. 
[`System.register(['process'], function () {`](dist/rollup/main.js#L1)
This dependency is not used anywhere in the emitted code body and It works after manually removing it.

JSPM build works out of the box.
[`System.register([], function () {`](dist/jspm/main.js#L1)

The issue is same with other modules formats than "system".

Since jspm build output doesn’t have this issue, I feel it’s issue with this plugin.

I have following system setup 
```sh
➜  jspm-react-rollup git:(master) node -v
v10.16.0
➜  jspm-react-rollup git:(master) npm -v
6.9.0
➜  jspm-react-rollup git:(master) jspm -v
2.0.0-beta.6
Running against local jspm install.
```

**Comment by guybedford** [comment]
Thanks so much for posting.

I just tried out this exact case, and looking at `dist/jspm/main.js` and `dist/rollup/main.js` they both contained `System.register([]` without the process dependency for me.

Note that jspm itself just wraps rollup-plugin-jspm and calls it - https://github.com/jspm/jspm-cli/blob/master/src/build/index.ts.

I'm wondering if there might be some other interaction causing this? An old install that hasn't been updated? Or a nested project that isn't a clean clone?

**Comment by fusionstrings** [comment]
I tried to reproduce in a clean environment.
Here is reproduced version https://glitch.com/edit/#!/join/c47ef1f9-39b8-49cf-b20d-5029ed5fe79c

**Comment by fusionstrings** [comment]
Issue was wrong plugin configuration. I’d set [`node: true`](https://github.com/fusionstrings/jspm-react-rollup/blob/master/rollup.config.js#L13).

**Comment by guybedford** [comment]
:+1:
